import { Card } from 'antd'
import { withApollo } from '../../src/apollo'

// Created with https://www.avodocs.com

function PrivacyPolicyPage() {
  return (
    <Card>
      <div>
        <p className="c5 c11">
          <span className="c30 c16"></span>
        </p>
      </div>
      <h1 className="c35">
        <span className="c8">PRIVACY POLICY</span>
      </h1>
      <p className="c19">
        <span className="c16 c30">&nbsp;</span>
      </p>
      <p className="c19">
        <span className="c3">Effective date: 08/11/2022</span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0 start" start={1}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Introduction</span>
        </li>
      </ol>
      <p className="c1 c5">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">Welcome to&nbsp;</span>
        <span className="c8">ChainJet</span>
        <span className="c3">.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          ChainJet&nbsp;(&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;)
          operates&nbsp;https://chainjet.io&nbsp;(hereinafter referred to as &ldquo;
        </span>
        <span className="c8">Service</span>
        <span className="c3">&rdquo;).</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Our Privacy Policy governs your visit to&nbsp;https://chainjet.io, and explains how we collect, safeguard and
          disclose information that results from your use of our Service.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We use your data to provide and improve Service. By using Service, you agree to the collection and use of
          information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in
          this Privacy Policy have the same meanings as in our Terms and Conditions.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">Our Terms and Conditions (&ldquo;</span>
        <span className="c8">Terms</span>
        <span className="c3">
          &rdquo;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us
          (&ldquo;
        </span>
        <span className="c8">agreement</span>
        <span className="c3">&rdquo;).</span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={2}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Definitions</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c8">SERVICE&nbsp;</span>
        <span className="c3">means the&nbsp;https://chainjet.io website&nbsp;operated by&nbsp;ChainJet.</span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c8">PERSONAL DATA</span>
        <span className="c3">
          &nbsp;means data about a living individual who can be identified from those data (or from those and other
          information either in our possession or likely to come into our possession).
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c8">USAGE DATA</span>
        <span className="c3">
          &nbsp;is data collected automatically either generated by the use of Service or from Service infrastructure
          itself (for example, the duration of a page visit).
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c8">COOKIES</span>
        <span className="c3">&nbsp;are small files stored on your device (computer or mobile device).</span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c8">DATA CONTROLLER</span>
        <span className="c3">
          &nbsp;means a natural or legal person who (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose
          of this Privacy Policy, we are a Data Controller of your data.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c26">DATA PROCESSORS (OR SERVICE PROVIDERS)</span>
        <span className="c3">
          &nbsp;means any natural or legal person who processes the data on behalf of the Data Controller. We may use
          the services of various Service Providers in order to process your data more effectively.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c26">DATA SUBJECT&nbsp;</span>
        <span className="c3">is any living individual who is the subject of Personal Data.</span>
      </p>
      <p className="c1 c10">
        <span className="c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c26">THE USER&nbsp;</span>
        <span className="c3">
          is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal
          Data.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={3}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Information Collection and Use</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We collect several different types of information for various purposes to provide and improve our Service to
          you.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={4}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Types of Data Collected</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c8">Personal Data</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          While using our Service, we may ask you to provide us with certain personally identifiable information that
          can be used to contact or identify you (&ldquo;
        </span>
        <span className="c8">Personal Data</span>
        <span className="c3">&rdquo;). Personally identifiable information may include, but is not limited to:</span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_26-1 start" start={1}>
        <li className="c0 li-bullet-1">
          <span className="c3">Email address</span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other
          information that may be of interest to you. You may opt out of receiving any, or all, of these communications
          from us&nbsp;by following the unsubscribe link or by emailing at&nbsp;support@chainjet.io.
        </span>
      </p>
      <p className="c1 c20">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c8">Usage Data</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We may also collect information that your browser sends whenever you visit our Service or when you access
          Service by or through a mobile device (&ldquo;
        </span>
        <span className="c8">Usage Data</span>
        <span className="c3">&rdquo;).</span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          This Usage Data may include information such as your computer&#39;s Internet Protocol address (e.g. IP
          address), browser type, browser version, the pages of our Service that you visit, the time and date of your
          visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          When you access Service with a mobile device, this Usage Data may include information such as the type of
          mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile
          operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic
          data.
        </span>
      </p>
      <p className="c1 c20">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c8">Tracking Cookies Data</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We use cookies and similar tracking technologies to track the activity on our Service and we hold certain
          information.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are
          sent to your browser from a website and stored on your device. Other tracking technologies are also used such
          as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if
          you do not accept cookies, you may not be able to use some portions of our Service.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">Examples of Cookies we use:</span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-1 start" start={1}>
        <li className="c0 li-bullet-1">
          <span className="c8">Session Cookies:</span>
          <span className="c3">&nbsp;We use Session Cookies to operate our Service.</span>
        </li>
      </ol>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-1" start={2}>
        <li className="c0 li-bullet-2">
          <span className="c8">Preference Cookies:</span>
          <span className="c3">&nbsp;We use Preference Cookies to remember your preferences and various settings.</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-1" start={3}>
        <li className="c0 li-bullet-2">
          <span className="c8">Security Cookies:</span>
          <span className="c3">&nbsp;We use Security Cookies for security purposes.</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-1" start={4}>
        <li className="c0 li-bullet-1">
          <span className="c8">Advertising Cookies:</span>
          <span className="c3">
            &nbsp;Advertising Cookies are used to serve you with advertisements that may be relevant to you and your
            interests.
          </span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={5}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Use of Data</span>
        </li>
      </ol>
      <p className="c1 c5">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">ChainJet&nbsp;uses the collected data for various purposes:</span>
      </p>
      <p className="c1 c5">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1 start" start={1}>
        <li className="c0 li-bullet-1">
          <span className="c3">to provide and maintain our Service;</span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={2}>
        <li className="c0 li-bullet-1">
          <span className="c3">to notify you about changes to our Service; </span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={3}>
        <li className="c0 li-bullet-2">
          <span className="c3">
            to allow you to participate in interactive features of our Service when you choose to do so;
          </span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={4}>
        <li className="c0 li-bullet-1">
          <span className="c3">to provide customer support; </span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={5}>
        <li className="c0 li-bullet-2">
          <span className="c3">to gather analysis or valuable information so that we can improve our Service;</span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={6}>
        <li className="c0 li-bullet-1">
          <span className="c3">to monitor the usage of our Service;</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={7}>
        <li className="c0 li-bullet-1">
          <span className="c3">to detect, prevent and address technical issues;</span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={8}>
        <li className="c0 li-bullet-2">
          <span className="c3">to fulfill any other purpose for which you provide it;</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={9}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            to carry out our obligations and enforce our rights arising from any contracts entered into between you and
            us, including for billing and collection;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={10}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            to provide you with notices about your account and/or subscription, including expiration and renewal
            notices, email-instructions, etc.;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={11}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            to provide you with news, special offers and general information about other goods, services and events
            which we offer that are similar to those that you have already purchased or enquired about unless you have
            opted not to receive such information;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={12}>
        <li className="c0 li-bullet-1">
          <span className="c3">in any other way we may describe when you provide the information;</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_28-1" start={13}>
        <li className="c0 li-bullet-1">
          <span className="c3">for any other purpose with your consent. </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={6}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Retention of Data</span>
        </li>
      </ol>
      <p className="c1 c5">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy
          Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations
          (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter
          period, except when this data is used to strengthen the security or to improve the functionality of our
          Service, or we are legally obligated to retain this data for longer time periods.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={7}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Transfer of Data</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Your information, including Personal Data, may be transferred to &ndash; and maintained on &ndash; computers
          located outside of your state, province, country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          If you are located outside United States and choose to provide information to us, please note that we transfer
          the data, including Personal Data, to United States and process it there.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Your consent to this Privacy Policy followed by your submission of such information represents your agreement
          to that transfer.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10 c34">
        <span className="c3">
          ChainJet&nbsp;will take all the steps reasonably necessary to ensure that your data is treated securely and in
          accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation
          or a country unless there are adequate controls in place including the security of your data and other
          personal information.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={8}>
        <li className="c1 c5 c13 li-bullet-0">
          <span className="c14">Disclosure of Data</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">We may disclose personal information that we collect, or you provide:</span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-1 start" start={1}>
        <li className="c0 c5 li-bullet-2">
          <span className="c8">Disclosure for Law Enforcement.</span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">
          Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or
          in response to valid requests by public authorities.
        </span>
      </p>
      <p className="c19 c32">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-1" start={2}>
        <li className="c0 c5 li-bullet-2">
          <span className="c8">Business Transaction.</span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">
          If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be
          transferred.
        </span>
      </p>
      <p className="c19 c27">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-1" start={3}>
        <li className="c1 c5 c21 c31 li-bullet-3">
          <span className="c8">Other cases. We may disclose your information also:</span>
        </li>
      </ol>
      <p className="c1 c25 c5">
        <span className="c8">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2 start" start={1}>
        <li className="c1 c18 c24 li-bullet-4">
          <span className="c3">to our subsidiaries and affiliates;</span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2" start={2}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">
            to contractors, service providers, and other third parties we use to support our business;
          </span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2" start={3}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">to fulfill the purpose for which you provide it;</span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2" start={4}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">for the purpose of including your company&rsquo;s logo on our website;</span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2" start={5}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">for any other purpose disclosed by us when you provide the information;</span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2" start={6}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">with your consent in any other cases;</span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_29-2" start={7}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">
            if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the
            Company, our customers, or others.
          </span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={9}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Security of Data</span>
        </li>
      </ol>
      <p className="c1 c5">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          The security of your data is important to us but remember that no method of transmission over the Internet or
          method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect
          your Personal Data, we cannot guarantee its absolute security.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={10}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data
          protection rights, covered by GDPR. &ndash; See more at{' '}
        </span>
        <span className="c15 c16 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://eur-lex.europa.eu/eli/reg/2016/679/oj&amp;sa=D&amp;source=editors&amp;ust=1660239698737420&amp;usg=AOvVaw3hj0xUx2_oTLf5qCG5VcT-"
          >
            https://eur-lex.europa.eu/eli/reg/2016/679/oj
          </a>
        </span>
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal
          Data.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our
          systems, please email us at support@chainjet.io.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">In certain circumstances, you have the following data protection rights:</span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_30-1 start" start={1}>
        <li className="c0 li-bullet-1">
          <span className="c3">the right to access, update or to delete the information we have on you;</span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_30-1" start={2}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            the right of rectification. You have the right to have your information rectified if that information is
            inaccurate or incomplete;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_30-1" start={3}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            the right to object. You have the right to object to our processing of your Personal Data;
          </span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_30-1" start={4}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            the right of restriction. You have the right to request that we restrict the processing of your personal
            information;
          </span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_30-1" start={5}>
        <li className="c0 li-bullet-2">
          <span className="c3">
            the right to data portability. You have the right to be provided with a copy of your Personal Data in a
            structured, machine-readable and commonly used format;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_30-1" start={6}>
        <li className="c0 li-bullet-2">
          <span className="c3">
            the right to withdraw consent.&nbsp;You also have the right to withdraw your consent at any time where we
            rely on your consent to process your personal information;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Please note that we may ask you to verify your identity before responding to such requests. Please note, we
          may not able to provide Service without some necessary data.
        </span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          You have the right to complain to a Data Protection Authority about our collection and use of your Personal
          Data. For more information, please contact your local data protection authority in the European Economic Area
          (EEA).
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={11}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          CalOPPA is the first state law in the nation to require commercial websites and online services to post a
          privacy policy. The law&rsquo;s reach stretches well beyond California to require a person or company in the
          United States (and conceivable the world) that operates websites collecting personally identifiable
          information from California consumers to post a conspicuous privacy policy on its website stating exactly the
          information being collected and those individuals with whom it is being shared, and to comply with this
          policy. &ndash; See more at:{' '}
        </span>
        <span className="c15 c16 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/&amp;sa=D&amp;source=editors&amp;ust=1660239698739898&amp;usg=AOvVaw3Z-btante-nUQlYZiYLhw2"
          >
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </a>
        </span>
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">According to CalOPPA we agree to the following:</span>
      </p>
      <p className="c1 c5">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_31-1 start" start={1}>
        <li className="c0 li-bullet-1">
          <span className="c3">users can visit our site anonymously;</span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_31-1" start={2}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            our Privacy Policy link includes the word &ldquo;Privacy&rdquo;, and can easily be found on the page
            specified above on the home page of our website;
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_31-1" start={3}>
        <li className="c0 li-bullet-1">
          <span className="c3">users will be notified of any privacy policy changes on our Privacy Policy Page;</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_31-1" start={4}>
        <li className="c0 li-bullet-1">
          <span className="c3">
            users are able to change their personal information by emailing us at support@chainjet.io.
          </span>
        </li>
      </ol>
      <p className="c1 c22">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">Our Policy on &ldquo;Do Not Track&rdquo; Signals:</span>
      </p>
      <p className="c1 c5">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser
          mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that
          you do not want to be tracked.
        </span>
      </p>
      <p className="c1 c5">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={12}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your
          data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and
          ask us:
        </span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_33-1 start" start={1}>
        <li className="c0 li-bullet-1">
          <span className="c8">What personal information we have about you</span>
          <span className="c3">. If you make this request, we will return to you:</span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2 start" start={1}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">The categories of personal information we have collected about you.</span>
        </li>
      </ol>
      <p className="c1 c18">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2" start={2}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">The categories of sources from which we collect your personal information.</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2" start={3}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">
            The business or commercial purpose for collecting or selling your personal information.
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2" start={4}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">The categories of third parties with whom we share personal information.</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2" start={5}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">The specific pieces of personal information we have collected about you.</span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2" start={6}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">
            A list of categories of personal information that we have sold, along with the category of any other company
            we sold it to. If we have not sold your personal information, we will inform you of that fact.
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_34-2" start={7}>
        <li className="c1 c18 c24 li-bullet-5">
          <span className="c3">
            A list of categories of personal information that we have disclosed for a business purpose, along with the
            category of any other company we shared it with.
          </span>
        </li>
      </ol>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c25">
        <span className="c3">
          Please note, you are entitled to ask us to provide you with this information up to two times in a rolling
          twelve-month period. When you make this request, the information provided may be limited to the personal
          information we collected about you in the previous 12&nbsp;months.
        </span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_33-1" start={2}>
        <li className="c0 li-bullet-1">
          <span className="c8">To delete your personal information</span>
          <span className="c3">
            . If you make this request, we will delete the personal information we hold about you as of the date of your
            request from our records and direct any service providers to do the same. In some cases, deletion may be
            accomplished through de-identification of the information. If you choose to delete your personal
            information, you may not be able to use certain functions that require your personal information to operate.
          </span>
          <span className="c8">&nbsp;</span>
        </li>
      </ol>
      <p className="c1 c17">
        <span className="c8">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_33-1" start={3}>
        <li className="c0 li-bullet-1">
          <span className="c8">To stop selling your personal information</span>
          <span className="c3">
            . We don&#39;t sell or rent your personal information to any third parties for any purpose. You are the only
            owner of your Personal Data and can request disclosure or deletion at any time.
          </span>
        </li>
      </ol>
      <p className="c1 c25">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c25">
        <span className="c3">
          Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you
          may not be able to participate in certain programs or membership services which require the usage of your
          personal information to function. But in no circumstances, we will discriminate against you for exercising
          your rights.
        </span>
      </p>
      <p className="c1 c25">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c25">
        <span className="c3">
          To exercise your California data protection rights described above, please send your request(s) by one of the
          following means:
        </span>
      </p>
      <p className="c1 c25">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c21">
        <span className="c3">By email: support@chainjet.io</span>
      </p>
      <p className="c1 c21">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c21">
        <span className="c3">By visiting this page on our website: https://chainjet.io</span>
      </p>
      <p className="c1 c21">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          Your data protection rights, described above, are covered by the CCPA, short for the California Consumer
          Privacy Act. To find out more, visit the official{' '}
        </span>
        <span className="c15 c16 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=http://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id%3D201720180AB375&amp;sa=D&amp;source=editors&amp;ust=1660239698744392&amp;usg=AOvVaw3q4DAcYfLAVn8h37eye6Kj"
          >
            California Legislative Information website
          </a>
        </span>
        <span className="c3">. The CCPA took effect on 01/01/2020. </span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={13}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Service Providers</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We may employ third party companies and individuals to facilitate our Service (&ldquo;
        </span>
        <span className="c8">Service Providers</span>
        <span className="c3">
          &rdquo;), provide Service on our behalf, perform Service-related services or assist us in analysing how our
          Service is used.
        </span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          These third parties have access to your Personal Data only to perform these tasks on our behalf and are
          obligated not to disclose or use it for any other purpose.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={14}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Analytics</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          We may use third-party Service Providers to monitor and analyze the use of our Service.
        </span>
      </p>
      <p className="c1 c5">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2 subtitle">
        <span className="c8">Google Analytics</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google
          uses the data collected to track and monitor the use of our Service. This data is shared with other Google
          services. Google may use the collected data to contextualise and personalise the ads of its own advertising
          network.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:{' '}
        </span>
        <span className="c15 c16 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://policies.google.com/privacy?hl%3Den&amp;sa=D&amp;source=editors&amp;ust=1660239698745905&amp;usg=AOvVaw3alzFLRv_Nnqt8AodP2Elr"
          >
            https://policies.google.com/privacy?hl=en
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c16 c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">We also encourage you to review the Google&#39;s policy for safeguarding your data: </span>
        <span className="c15 c16 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://support.google.com/analytics/answer/6004245&amp;sa=D&amp;source=editors&amp;ust=1660239698746256&amp;usg=AOvVaw3jc4SQXle2el1fz0gpYTHE"
          >
            https://support.google.com/analytics/answer/6004245
          </a>
        </span>
        <span className="c3">.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c8">Cloudflare analytics</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          Cloudflare analytics is a web analytics service operated by Cloudflare Inc. Read the Privacy Policy here:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://www.cloudflare.com/privacypolicy/&amp;sa=D&amp;source=editors&amp;ust=1660239698746622&amp;usg=AOvVaw2PMttJTPW51st6qD8MCyBQ"
          >
            https://www.cloudflare.com/privacypolicy/
          </a>
        </span>
        <span className="c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2 subtitle">
        <span className="c8">Mixpanel</span>
      </p>
      <p className="c1 c10">
        <span className="c3">Mixpanel is provided by Mixpanel Inc.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of
          Mixpanel service, please visit this page:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://mixpanel.com/optout/&amp;sa=D&amp;source=editors&amp;ust=1660239698747245&amp;usg=AOvVaw1yLQ3gXoj9OgtHMtro5Q2A"
          >
            https://mixpanel.com/optout/
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c12 c15">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          For more information on what type of information Mixpanel collects, please visit the Terms of Use page of
          Mixpanel:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://mixpanel.com/terms/&amp;sa=D&amp;source=editors&amp;ust=1660239698747566&amp;usg=AOvVaw3SoxyGE9eY-A_xF4jvGY5Q"
          >
            https://mixpanel.com/terms/
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c12">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={15}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">CI/CD tools</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          We may use third-party Service Providers to automate the development process of our Service.
        </span>
      </p>
      <p className="c1 c2">
        <span className="c8">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c8">GitHub</span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">GitHub is provided by GitHub, Inc.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          GitHub is a development platform to host and review code, manage projects, and build software.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          For more information on what data GitHub collects for what purpose and how the protection of the data is
          ensured, please visit GitHub Privacy Policy page:
        </span>
        <span className="c15 c16 c12">&nbsp;</span>
        <span className="c15 c16 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://help.github.com/en/articles/github-privacy-statement&amp;sa=D&amp;source=editors&amp;ust=1660239698748556&amp;usg=AOvVaw0_onv3Zk5I7IY3ec3hSWaL"
          >
            https://help.github.com/en/articles/github-privacy-statement
          </a>
        </span>
        <span className="c3">.</span>
      </p>
      <p className="c19">
        <span className="c8 c23">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={16}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Behavioral Remarketing</span>
        </li>
      </ol>
      <p className="c1 c5">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          ChainJet&nbsp;uses remarketing services to advertise on third party websites to you after you visited our
          Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past
          visits to our Service.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2 subtitle">
        <span className="c8">Google Ads (AdWords)</span>
      </p>
      <p className="c1 c10">
        <span className="c3">Google Ads (AdWords) remarketing service is provided by Google Inc.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by
          visiting the Google Ads Settings page:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=http://www.google.com/settings/ads&amp;sa=D&amp;source=editors&amp;ust=1660239698749498&amp;usg=AOvVaw3j8Xre6V2UmMv3zdQxXYhc"
          >
            http://www.google.com/settings/ads
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          Google also recommends installing the Google Analytics Opt-out Browser Add-on &ndash;{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://tools.google.com/dlpage/gaoptout&amp;sa=D&amp;source=editors&amp;ust=1660239698749846&amp;usg=AOvVaw0AIqQ_lADAkKiTQAO9RsDd"
          >
            https://tools.google.com/dlpage/gaoptout
          </a>
        </span>
        <span className="c3">
          &nbsp;&ndash; for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability
          to prevent their data from being collected and used by Google Analytics.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://policies.google.com/privacy?hl%3Den&amp;sa=D&amp;source=editors&amp;ust=1660239698750173&amp;usg=AOvVaw0FSq-l_foxzYvqnFOyybU3"
          >
            https://policies.google.com/privacy?hl=en
          </a>
        </span>
      </p>
      <p className="c1 c10 subtitle">
        <span className="c8">&nbsp;</span>
      </p>
      <p className="c1 c2 subtitle">
        <span className="c8">Bing Ads Remarketing</span>
      </p>
      <p className="c1 c10">
        <span className="c3">Bing Ads remarketing service is provided by Microsoft Inc.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">You can opt-out of Bing Ads interest-based ads by following their instructions: </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads&amp;sa=D&amp;source=editors&amp;ust=1660239698750836&amp;usg=AOvVaw286wXLZ4G_QdBMEKoW6Zh3"
          >
            https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          You can learn more about the privacy practices and policies of Microsoft by visiting their Privacy Policy
          page:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://privacy.microsoft.com/en-us/PrivacyStatement&amp;sa=D&amp;source=editors&amp;ust=1660239698751192&amp;usg=AOvVaw0bM4wKf1bvzs0p3CSOi6CC"
          >
            https://privacy.microsoft.com/en-us/PrivacyStatement
          </a>
        </span>
      </p>
      <p className="c1 c10 subtitle">
        <span className="c8">&nbsp;</span>
      </p>
      <p className="c1 c2 subtitle">
        <span className="c8">Twitter</span>
      </p>
      <p className="c1 c10">
        <span className="c3">Twitter remarketing service is provided by Twitter Inc.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          You can opt-out from Twitter&#39;s interest-based ads by following their instructions:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://support.twitter.com/articles/20170405&amp;sa=D&amp;source=editors&amp;ust=1660239698751843&amp;usg=AOvVaw16BVObO9093cg0qEQTAvit"
          >
            https://support.twitter.com/articles/20170405
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://twitter.com/privacy&amp;sa=D&amp;source=editors&amp;ust=1660239698752167&amp;usg=AOvVaw3gwJJxgMqCp7NCGXOkTmw4"
          >
            https://twitter.com/privacy
          </a>
        </span>
      </p>
      <p className="c1 c10 subtitle">
        <span className="c8">&nbsp;</span>
      </p>
      <p className="c1 c2 subtitle">
        <span className="c8">Facebook</span>
      </p>
      <p className="c1 c10">
        <span className="c3">Facebook remarketing service is provided by Facebook Inc.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          You can learn more about interest-based advertising from Facebook by visiting this page:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://www.facebook.com/help/164968693837950&amp;sa=D&amp;source=editors&amp;ust=1660239698752763&amp;usg=AOvVaw1tOBzaylp4lRTdiJFgGRIn"
          >
            https://www.facebook.com/help/164968693837950
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          To opt-out from Facebook&#39;s interest-based ads, follow these instructions from Facebook:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://www.facebook.com/help/568137493302217&amp;sa=D&amp;source=editors&amp;ust=1660239698753114&amp;usg=AOvVaw2a-rzXHZ2C1Ccj-ShzGN3R"
          >
            https://www.facebook.com/help/568137493302217
          </a>
        </span>
      </p>
      <p className="c1 c10">
        <span className="c15 c12">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the
          Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the
          Digital Advertising Alliance in the USA{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=http://www.aboutads.info/choices/&amp;sa=D&amp;source=editors&amp;ust=1660239698753469&amp;usg=AOvVaw3_XkYqn3HqTkSBPv0_jDMw"
          >
            http://www.aboutads.info/choices/
          </a>
        </span>
        <span className="c12">, the Digital Advertising Alliance of Canada in Canada </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=http://youradchoices.ca/&amp;sa=D&amp;source=editors&amp;ust=1660239698753643&amp;usg=AOvVaw24w1QOwwJWZeBtWycUed2Z"
          >
            http://youradchoices.ca/
          </a>
        </span>
        <span className="c12">&nbsp;or the European Interactive Digital Advertising Alliance in Europe </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=http://www.youronlinechoices.eu/&amp;sa=D&amp;source=editors&amp;ust=1660239698753819&amp;usg=AOvVaw0cIQF-qdGZmitVdr9ZLhAn"
          >
            http://www.youronlinechoices.eu/
          </a>
        </span>
        <span className="c3">, or opt-out using your mobile device settings.</span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c12">
          For more information on the privacy practices of Facebook, please visit Facebook&#39;s Data Policy:{' '}
        </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://www.facebook.com/privacy/explanation&amp;sa=D&amp;source=editors&amp;ust=1660239698754194&amp;usg=AOvVaw0wPNtVkyuFOEcYbGgDFKGs"
          >
            https://www.facebook.com/privacy/explanation
          </a>
        </span>
      </p>
      <p className="c1 c10 subtitle">
        <span className="c8">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={17}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Payments</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We may provide paid products and/or services within Service. In that case, we use third-party services for
          payment processing (e.g. payment processors).
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We will not store or collect your payment card details. That information is provided directly to our
          third-party payment processors whose use of your personal information is governed by their Privacy Policy.
          These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards
          Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS
          requirements help ensure the secure handling of payment information.
        </span>
      </p>
      <p className="c1 c10">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">The payment processors we work with are:</span>
      </p>
      <p className="c4">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c4 c5 subtitle">
        <span className="c8">PayPal or Braintree:</span>
      </p>
      <p className="c4">
        <span className="c12">Their Privacy Policy can be viewed at&nbsp;</span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://www.paypal.com/webapps/mpp/ua/privacy-full&amp;sa=D&amp;source=editors&amp;ust=1660239698755208&amp;usg=AOvVaw2f1PYl_bVBqwNKu4pvz8pA"
          >
            https://www.paypal.com/webapps/mpp/ua/privacy-full
          </a>
        </span>
      </p>
      <p className="c4">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c4 c5 subtitle">
        <span className="c8">Stripe:</span>
      </p>
      <p className="c4">
        <span className="c12">Their Privacy Policy can be viewed at: </span>
        <span className="c15 c12">
          <a
            className="c7"
            href="https://www.google.com/url?q=https://stripe.com/us/privacy&amp;sa=D&amp;source=editors&amp;ust=1660239698755644&amp;usg=AOvVaw1uhYkYy4T2QDBKCnI6mwQR"
          >
            https://stripe.com/us/privacy
          </a>
        </span>
      </p>
      <p className="c4">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={18}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Links to Other Sites</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          Our Service may contain links to other sites that are not operated by us. If you click a third party link, you
          will be directed to that third party&#39;s site. We strongly advise you to review the Privacy Policy of every
          site you visit.
        </span>
      </p>
      <p className="c1">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We have no control over and assume no responsibility for the content, privacy policies or practices of any
          third party sites or services.
        </span>
      </p>
      <p className="c4">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={19}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Children&#39;s Privacy</span>
        </li>
      </ol>
      <p className="c19">
        <span className="c3 c9">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c12">Our Services are not intended for use by children under the age of 18 (&ldquo;</span>
        <span className="c26">Child</span>
        <span className="c12">&rdquo; or &ldquo;</span>
        <span className="c26">Children</span>
        <span className="c3">&rdquo;). </span>
      </p>
      <p className="c1 c2">
        <span className="c12">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">
          We do not knowingly collect personally identifiable information from Children under 18. If you become aware
          that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected
          Personal Data from Children without verification of parental consent, we take steps to remove that information
          from our servers.
        </span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={20}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Changes to This Privacy Policy</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
          Privacy Policy on this page.
        </span>
      </p>
      <p className="c1">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
          effective and update &ldquo;effective date&rdquo; at the top of this Privacy Policy.
        </span>
      </p>
      <p className="c1">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c1 c10">
        <span className="c3">
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
          effective when they are posted on this page.
        </span>
      </p>
      <p className="c19">
        <span className="c3">&nbsp;</span>
      </p>
      <ol className="c6 lst-kix_list_27-0" start={21}>
        <li className="c1 c13 c5 li-bullet-0">
          <span className="c14">Contact Us</span>
        </li>
      </ol>
      <p className="c1 c2">
        <span className="c14">&nbsp;</span>
      </p>
      <p className="c1 c2">
        <span className="c3">If you have any questions about this Privacy Policy, please contact us:</span>
      </p>
      <p className="c1 c2">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c4">
        <span className="c3">By email: support@chainjet.io.</span>
      </p>
      <p className="c4">
        <span className="c3">&nbsp;</span>
      </p>
      <p className="c4">
        <span className="c3">By visiting this page on our website: https://chainjet.io.</span>
      </p>
      <p className="c4">
        <span className="c3">&nbsp;</span>
      </p>
      <div>
        <p className="c5 c29">
          <span className="c3"></span>
        </p>
      </div>
    </Card>
  )
}

export default withApollo(PrivacyPolicyPage, { useLayout: false })
